CREATE DATABASE StoreManagementSystem;
GO

USE StoreManagementSystem;

CREATE TABLE Category
(
	Id INTEGER PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL
);

CREATE TABLE Product
(
	Id INTEGER PRIMARY KEY IDENTITY,
	ProductName NVARCHAR(50) NOT NULL,
	Brand NVARCHAR(50) NOT NULL,
	ExpiryDate DATE NOT NULL,
	Price DECIMAL NOT NULL
);

CREATE TABLE Store
(
	Id INTEGER PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	ProductId INTEGER FOREIGN KEY REFERENCES Product(Id)
);

CREATE TABLE Users 
(
	Id INTEGER PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	EmailAddress VARCHAR(50) NOT NULL,
	[Password] NVARCHAR(64) NOT NULL,
	StoreId INTEGER FOREIGN KEY REFERENCES Store(Id)
);

CREATE TABLE ProductCategory
(
	Id INTEGER PRIMARY KEY IDENTITY,
	ProductId INTEGER FOREIGN KEY REFERENCES Product(Id),
	CategoryId INTEGER FOREIGN KEY REFERENCES Category(Id)
);